 &lt;div class="wrap"&gt;
			     &lt;div class="img_wrap"&gt;
			         &lt;img src="img/hero1.jpg" alt="" /&gt;
			         &lt;img src="img/hero2.jpg" alt="" /&gt;
			         &lt;img src="img/hero3.jpg" alt="" /&gt;
			         &lt;img src="img/hero4.jpg" alt="" /&gt;
			         &lt;img src="img/hero5.jpg" alt="" /&gt;
			         &lt;img src="img/hero6.jpg" alt="" /&gt;
			         &lt;img src="img/hero7.jpg" alt="" /&gt;
			         &lt;img src="img/hero8.jpg" alt="" /&gt;
			         &lt;img src="img/hero9.jpg" alt="" /&gt;
			         &lt;img src="img/hero10.jpg" alt="" /&gt;
			         &lt;img src="img/hero11.jpg" alt="" /&gt;
			         &lt;img src="img/hero12.jpg" alt="" /&gt;
			     &lt;/div&gt;
			 &lt;/div&gt;